-- MySQL Script generated by MySQL Workbench
-- Mon Jun  8 10:46:55 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SeuNutri
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SeuNutri` ;

-- -----------------------------------------------------
-- Schema SeuNutri
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SeuNutri` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `SeuNutri` ;

-- -----------------------------------------------------
-- Table `SeuNutri`.`Ranque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SeuNutri`.`Ranque` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SeuNutri`.`Ranque` (
  `IMC` INT NOT NULL,
  `id_ranque` INT NOT NULL,
  `pontuacao` DOUBLE NOT NULL,
  `Ranquecol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_ranque`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SeuNutri`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SeuNutri`.`Usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SeuNutri`.`Usuario` (
  `CPF` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Localização` VARCHAR(45) NOT NULL,
  `Idade` INT NOT NULL,
  `Peso` DOUBLE NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Sexo` VARCHAR(45) NOT NULL,
  `Id_ranque` INT NOT NULL,
  PRIMARY KEY (`CPF`),
  CONSTRAINT `fk_Usuario_Ranque1`
    FOREIGN KEY (`Id_ranque`)
    REFERENCES `SeuNutri`.`Ranque` (`id_ranque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Usuario_Ranque1_idx` ON `SeuNutri`.`Usuario` (`Id_ranque` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SeuNutri`.`Pratos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SeuNutri`.`Pratos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SeuNutri`.`Pratos` (
  `idPratos` INT NOT NULL,
  `Ingredientes` VARCHAR(45) NOT NULL,
  `valorNutricional` VARCHAR(45) NOT NULL,
  `Receita` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPratos`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SeuNutri`.`Ficha`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SeuNutri`.`Ficha` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SeuNutri`.`Ficha` (
  `IMC` INT NOT NULL,
  `Peso` DOUBLE NOT NULL,
  `Ranque` VARCHAR(45) NOT NULL,
  `Usuario_CPF` INT NOT NULL,
  `Id_prato` INT NOT NULL,
  `Id_ranque` INT NOT NULL,
  PRIMARY KEY (`Usuario_CPF`),
  CONSTRAINT `fk_Ficha_Usuario`
    FOREIGN KEY (`Usuario_CPF`)
    REFERENCES `SeuNutri`.`Usuario` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ficha_Pratos1`
    FOREIGN KEY (`Id_prato`)
    REFERENCES `SeuNutri`.`Pratos` (`idPratos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ficha_Ranque1`
    FOREIGN KEY (`Id_ranque`)
    REFERENCES `SeuNutri`.`Ranque` (`id_ranque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Ficha_Pratos1_idx` ON `SeuNutri`.`Ficha` (`Id_prato` ASC) ;

SHOW WARNINGS;
CREATE INDEX `fk_Ficha_Ranque1_idx` ON `SeuNutri`.`Ficha` (`Id_ranque` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
